# Top-level Cargo.toml - mostly just tells vscode to look into the subdirectories


[workspace]
members = [
  "common",
  "desktop",
  "desktop/web-gui",
  "libconntrack",
  "probe-o-matic",
  "storage-server",
  "webserver",
  "webserver/web-client",
]
resolver = "2"
