# Top-level Cargo.toml - mostly just tells vscode to look into the subdirectories


[workspace]
members = [ "libconntrack", "webserver", "webserver/web-client", "desktop", "desktop/web-gui"]
resolver = "2"
