# Top-level Cargo.toml - mostly just tells vscode to look into the subdirectories

[profile.release]
# always build release builds with debug symbols
debug = true

[workspace]
members = [
  "common",
  "desktop",
  "desktop/web-gui",
  "ip-asn-lookup",
  "libconntrack",
  "probe-o-matic",
  "storage-server",
  "webserver",
  "webserver/web-client",
]
resolver = "2"
