# Used for fly.io deployment - doesn't actually work because we can't send (recv?) raw pcakets!?
# fly.toml app configuration file generated for netdebug-demo on 2023-07-22T06:11:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "netdebug-demo"
primary_region = "ams"

[http_service]
  internal_port = 3030
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
