#!/bin/bash


# ANSI color escape codes
BRED="\033[1;31m"
DEFCOLOR="\033[0;39m"

printred() {
    echo -ne $BRED
    echo -n $@
    echo -e $DEFCOLOR
}


cargo fmt -- --check 
result=$?
if [[ ${result} -ne 0 ]] ; then
    printred ' There are some code style issues, run `cargo fmt` first.'
    exit 1
fi

npx prettier@3.0.0 -c . 
result=$?
if [[ ${result} -ne 0 ]] ; then
    printred ' There are some code style issues, run `npx prettier@3.0.0 -w .` first.'
    printred ' If this prettier run disagrees with the one on github actions, check the version numbers of prettier.'
    exit 1
fi



exit 0
