#!/bin/bash


# this needs to be updated for each new directory

diff=$(cd web/webserver && cargo fmt -- --check)
result=$?

if [[ ${result} -ne 0 ]] ; then
    cat <<\EOF
There are some code style issues, run `cargo fmt` first.
EOF
    exit 1
fi

exit 0
